// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('test', function() {
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('test', async function() {
    await driver.get("http://localhost:3000/add")
    await driver.manage().window().setRect({ width: 1235, height: 1040 })
    await driver.findElement(By.id("title")).click()
    await driver.findElement(By.id("title")).sendKeys("hey brothers avicci the song")
    await driver.findElement(By.id("description")).click()
    await driver.findElement(By.id("description")).sendKeys("i need to listen to this song again til i die of thirst, which may take 7 days aproximatly")
    await driver.findElement(By.css(".btn")).click()
  })
})
